# Generated by Django 3.0.7 on 2020-11-30 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('type', models.CharField(choices=[('PLAYER', 'Player'), ('COACH', 'Coach')], default='PLAYER', max_length=50, verbose_name='Type')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(default='https://ih1.redbubble.net/image.702995522.8412/flat,750x,075,f-pad,750x1000,f8f8f8.jpg', max_length=2000)),
                ('age', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('club', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('gradyear', models.CharField(max_length=200)),
                ('gpa', models.CharField(max_length=200)),
                ('height', models.CharField(default='', max_length=200)),
                ('weight', models.CharField(default='', max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('summary', models.TextField(default='', max_length=2000)),
                ('skills', models.TextField(default='', max_length=2000)),
                ('highlight', models.FileField(blank=True, default='', null=True, upload_to='post_files')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoachMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(default='https://st2.depositphotos.com/1338217/6803/v/950/depositphotos_68039059-stock-illustration-soccer-coach-with-ball.jpg', max_length=2000)),
                ('state', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('experience', models.TextField(max_length=2000)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('requirements', models.TextField(max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('recruit.user',),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('recruit.user',),
        ),
    ]
